# Site
name: 'BITDNA Blog'
description: 'Technology News Blog for Tips, News and More'
logo: 'assets/images/bitdna-blog.png'
favicon: 'assets/images/favicon.ico'
#baseurl: '/mundana-theme-jekyll'
disqus: 'bitdna-blog'
email: 'salesp@bitdna.id'
mailchimp-list: 'https://okanemo.us19.list-manage.com/subscribe/post?u=c9e072742b02d9d0e80e7afcf&id=600c434a05'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    anastasia:
      name:           Anastasia
      site:           https://www.bitdna.id
      avatar:         //blog.bitdna.id/assets/images/avatar1.jpg
      bio:            "Hi, I'm Anastasia, currently I'm the writer in this blog, hope you like it!"
      #email:
      twitter:        https://twitter.com/BitDNA_io
      instagram:      https://www.instagram.com/bitdna_io/
      facebook:       https://www.facebook.com/bitdna/
      linkedin:       https://www.linkedin.com/company/bitdna/

    jane:
      name:           Jane
      site:           https://www.bitdna.id
      avatar:         //blog.bitdna.id/assets/images/avatar2.jpg
      bio:            "I'm an AI, that able to do work for keep posted an update in this blog"
      #email:          fakemail@gmail.com
      twitter:        https://twitter.com/BitDNA_io
      instagram:      https://www.instagram.com/bitdna_io/
      facebook:       https://www.facebook.com/bitdna/
      linkedin:       https://www.linkedin.com/company/bitdna/

# Defaults
defaults:



  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Anastasia
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Sitemap
sitemap:
  lastmod: 2014-01-23
  priority: 0.7
  changefreq: 'monthly'
  exclude: 'yes'


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
